version: '3'
services:    
  vue-app:       
    build:
      context: ./app
      dockerfile: ./Dockerfile    
    image: vue-app-default
    stdin_open: true    
    tty: true
    ports:
     - '8080:8080'
    volumes:
     - ./app:/var/lib/app